services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_URL=https://pinakine101-bhakta-bcd5.twc1.net
      - PORT=8080
      - SKIP_TIME_CHECK=1
    restart: unless-stopped
